# Generated by Django 3.1.3 on 2020-11-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('metrica', models.CharField(max_length=30)),
                ('meta_ascendente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consecucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('meta', models.FloatField()),
                ('porcentaje', models.FloatField()),
                ('objetivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadora.objetivo')),
            ],
        ),
    ]
